### ISSUE TITLE
workaround for azk bug

### ISSUE THREAD

**Issue by GilZ** [getjaco/jaco_init#4]
Docker changed their versioning scheme, in a way that breaks azk: https://github.com/azukiapp/azk/issues/700

I've added the following line to `jaco_init_linux.sh`:
```sh
export AZK_DOCKER_VERSION=1.13.1
```
and tried to open a pull request, but I don't have permissions for this repository.

**Comment by alexpusch** [comment]
cool. Actually you need to add the export into your .zshrc/.bashrc, otherwise it won't apply after restart

We'll fix you permissions

**Comment by itayadler** [comment]
Permissions fixed
